### ISSUE TITLE
Support for SPM

### ISSUE THREAD

**Issue by pozog** [seontechnologies/seon-ios-sdk-public#2]
Support for SPM (Swift Package Manager). Many popular frameworks now support Swift Package Manager

**Comment by ifoatov** [comment]
SPM can add dependencies as XCFramework witch supported from version 3.0.6, but I cannot find url of XCFramework 
Changeling from Readme.md:
3.0.6 - XCFramework support

**Comment by robertorsulics-seon** [comment]
Hey guys, sorry for the late reply! We have come out with a swift package for the iOS SDK, you can find it here : https://github.com/seontechnologies/seon-ios-sdk-swift-package
